spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: example
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              mapping:
                event: debug
